name: Daily Auto Commit

on:
  schedule:
    - cron: '5 0 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit
        run: |
          git config user.email "wahaj9167@gmail.com"
          git config user.name "syedwahajali2"
          echo "$(date)" >> log.txt
          git add .
          git commit -m "log: $(date)"
          git push
